import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import ExcelJS from 'exceljs'
import { sounds } from './sounds'

function timestamp() {
  const d = new Date()
  const pad = (n) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}_${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}`
}

const PAPER_SIZES = {
  a4: { w: 210, h: 297 },
  a3: { w: 297, h: 420 },
  a2: { w: 420, h: 594 },
  a1: { w: 594, h: 841 },
}

function addLogoToPDF(pdf, school, pageW) {
  if (!school?.logo) return 0
  try {
    const logoSize = 14
    const logoX = pageW / 2 - logoSize / 2
    const logoY = 4
    const isPng = school.logo.startsWith('data:image/png')
    const isJpg = school.logo.startsWith('data:image/jpeg') || school.logo.startsWith('data:image/jpg')
    if (isPng) {
      pdf.addImage(school.logo, 'PNG', logoX, logoY, logoSize, logoSize)
    } else if (isJpg) {
      pdf.addImage(school.logo, 'JPEG', logoX, logoY, logoSize, logoSize)
    } else {
      return 0
    }
    return logoSize + 4
  } catch (e) {
    console.warn('Failed to add logo to PDF:', e)
    return 0
  }
}

export function exportTimetablePDF({ title, subtitle, days, periods, rows, paperSize, orientation, school, periodLabel }) {
  const dims = PAPER_SIZES[paperSize]
  if (!dims) return

  const isLandscape = orientation === 'landscape'
  const pdf = new jsPDF({
    orientation,
    unit: 'mm',
    format: paperSize,
  })

  const pageW = pdf.internal.pageSize.getWidth()
  const pageH = pdf.internal.pageSize.getHeight()

  // Header
  let headerY = 15
  if (school?.name) {
    const logoOffset = addLogoToPDF(pdf, school, pageW)
    headerY = 15 + logoOffset
    pdf.setFontSize(16)
    pdf.setTextColor(30, 64, 175)
    pdf.text(school.name, pageW / 2, headerY, { align: 'center' })
    pdf.setFontSize(10)
    pdf.setTextColor(100, 100, 100)
    if (school.motto) pdf.text(school.motto, pageW / 2, headerY + 6, { align: 'center' })
    if (school.address) pdf.text(school.address, pageW / 2, headerY + 11, { align: 'center' })
    headerY += 16
  }

  // Title
  pdf.setFontSize(14)
  pdf.setTextColor(30, 64, 175)
  const titleY = school?.name ? headerY + 4 : 18
  pdf.text(title, pageW / 2, titleY, { align: 'center' })

  if (subtitle) {
    pdf.setFontSize(10)
    pdf.setTextColor(80, 80, 80)
    pdf.text(subtitle, pageW / 2, titleY + 5, { align: 'center' })
  }

  if (periodLabel) {
    pdf.setFontSize(9)
    pdf.setTextColor(100, 100, 100)
    pdf.text(periodLabel, pageW / 2, titleY + 10, { align: 'center' })
  }

  // Table
  const head = [['Day / Period', ...periods.filter(p => !p.isBreak).map(p => p.name)]]
  const body = days.map(day => {
    const row = [day]
    for (const p of periods) {
      if (p.isBreak) continue
      const cellData = rows[day]?.[p.id]
      row.push(cellData || '—')
    }
    return row
  })

  const tableStartY = school?.name ? (school?.logo ? 50 : 45) : 30
  const scale = pageW / 210
  const margin = 5 * scale
  const availableHeight = pageH - tableStartY - 10 * scale
  const totalRows = body.length + 1
  const rowHeight = availableHeight / totalRows
  autoTable(pdf, {
    head,
    body,
    startY: tableStartY,
    theme: 'grid',
    headStyles: {
      fillColor: [37, 99, 235],
      textColor: 255,
      fontSize: (isLandscape ? 8 : 7) * scale,
      halign: 'center',
      minCellHeight: rowHeight,
    },
    bodyStyles: {
      fontSize: (isLandscape ? 7 : 6) * scale,
      halign: 'center',
      valign: 'middle',
      minCellHeight: rowHeight,
    },
    alternateRowStyles: {
      fillColor: [239, 246, 255],
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 25 * scale, fillColor: [219, 234, 254] },
    },
    margin: { left: margin, right: margin },
  })

  // Footer
  const pageCount = pdf.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i)
    pdf.setFontSize(7)
    pdf.setTextColor(150, 150, 150)
    pdf.text(
      `Generated by Shikola Timetable Creator - Sepio Corp`,
      pageW / 2,
      pageH - 5,
      { align: 'center' }
    )
  }

  sounds.export()
  const filename = `${title.replace(/[^a-zA-Z0-9]/g, '_')}_${paperSize}_${orientation}_${timestamp()}.pdf`
  pdf.save(filename)
}

export function exportMasterPDF({ days, periods, timetables, paperSize, orientation, school, periodLabel, title }) {
  const dims = PAPER_SIZES[paperSize]
  if (!dims) return

  const pdf = new jsPDF({
    orientation,
    unit: 'mm',
    format: paperSize,
  })

  const pageW = pdf.internal.pageSize.getWidth()
  const pageH = pdf.internal.pageSize.getHeight()

  // Header
  let headerY = 15
  if (school?.name) {
    const logoOffset = addLogoToPDF(pdf, school, pageW)
    headerY = 15 + logoOffset
    pdf.setFontSize(16)
    pdf.setTextColor(30, 64, 175)
    pdf.text(school.name, pageW / 2, headerY, { align: 'center' })
    headerY += 8
  }

  pdf.setFontSize(14)
  pdf.setTextColor(30, 64, 175)
  const titleY = school?.name ? headerY : 18
  pdf.text(title || 'Master Timetable', pageW / 2, titleY, { align: 'center' })

  pdf.setFontSize(8)
  pdf.setTextColor(80, 80, 80)
  pdf.text(periodLabel || 'All timetables combined', pageW / 2, titleY + 5, { align: 'center' })

  const teachingPeriods = periods.filter(p => !p.isBreak)
  const head = [['Day / Period', ...teachingPeriods.map(p => p.name)]]
  const body = days.map(day => {
    const row = [day]
    for (const p of teachingPeriods) {
      const entries = timetables.filter(e => e.day === day && e.periodId === p.id)
      if (entries.length === 0) {
        row.push('—')
      } else {
        const cellText = entries.map(e => {
          const teacher = e.teacherName || ''
          const cls = e.className || ''
          const subject = e.subjectName || ''
          let line = `${cls}: ${subject} (${teacher})`
          if (e.secondaryClassName) {
            line += `\n  → ${e.secondaryClassName}: ${e.secondarySubjectName || ''} (${e.secondaryTeacherName || ''})`
          }
          return line
        }).join('\n')
        row.push(cellText)
      }
    }
    return row
  })

  const masterStartY = school?.name ? (school?.logo ? 40 : 35) : 28
  const masterScale = pageW / 210
  const masterMargin = 5 * masterScale
  const masterAvailableHeight = pageH - masterStartY - 10 * masterScale
  const masterTotalRows = body.length + 1
  const masterRowHeight = masterAvailableHeight / masterTotalRows
  autoTable(pdf, {
    head,
    body,
    startY: masterStartY,
    theme: 'grid',
    headStyles: {
      fillColor: [37, 99, 235],
      textColor: 255,
      fontSize: 7 * masterScale,
      halign: 'center',
      minCellHeight: masterRowHeight,
    },
    bodyStyles: {
      fontSize: 5 * masterScale,
      halign: 'center',
      valign: 'top',
      cellPadding: 1 * masterScale,
      minCellHeight: masterRowHeight,
    },
    alternateRowStyles: {
      fillColor: [239, 246, 255],
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 20 * masterScale, fillColor: [219, 234, 254] },
    },
    margin: { left: masterMargin, right: masterMargin },
  })

  // Footer
  pdf.setFontSize(7)
  pdf.setTextColor(150, 150, 150)
  pdf.text('Generated by Shikola Timetable Creator - Sepio Corp', pageW / 2, pageH - 5, { align: 'center' })

  sounds.export()
  pdf.save(`Master_Timetable_${paperSize}_${orientation}_${timestamp()}.pdf`)
}

const thinBorder = {
  top: { style: 'thin', color: { argb: 'FFB0B0B0' } },
  left: { style: 'thin', color: { argb: 'FFB0B0B0' } },
  bottom: { style: 'thin', color: { argb: 'FFB0B0B0' } },
  right: { style: 'thin', color: { argb: 'FFB0B0B0' } },
}

const headerFill = {
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: 'FF2563EB' },
}

const dayFill = {
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: 'FFDBEAFE' },
}

const altFill = {
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: 'FFEFF6FF' },
}

async function saveWorkbook(workbook, filename) {
  const buffer = await workbook.xlsx.writeBuffer()
  const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  link.click()
  URL.revokeObjectURL(url)
}

export async function exportCSV({ title, days, periods, rows }) {
  const teachingPeriods = periods.filter(p => !p.isBreak)
  const wb = new ExcelJS.Workbook()
  const ws = wb.addWorksheet('Timetable')

  const headers = ['Day / Period', ...teachingPeriods.map(p => `${p.name}\n(${p.start}-${p.end})`)]
  const headerRow = ws.addRow(headers)
  headerRow.height = 30
  headerRow.eachCell((cell, colNumber) => {
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 11 }
    cell.fill = headerFill
    cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true }
    cell.border = thinBorder
  })

  days.forEach((day, dayIdx) => {
    const rowData = [day]
    for (const p of teachingPeriods) {
      const cellText = rows[day]?.[p.id]
      if (cellText) {
        const lines = cellText.split('\n').filter(l => l.trim())
        rowData.push(lines.join('\n'))
      } else {
        rowData.push('—')
      }
    }
    const row = ws.addRow(rowData)
    row.height = 45
    row.eachCell((cell, colNumber) => {
      cell.border = thinBorder
      cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true }
      if (colNumber === 1) {
        cell.font = { bold: true, color: { argb: 'FF1E40AF' } }
        cell.fill = dayFill
      } else {
        cell.font = { size: 10 }
        if (dayIdx % 2 === 1) cell.fill = altFill
      }
    })
  })

  ws.columns.forEach((col, i) => {
    col.width = i === 0 ? 18 : 28
  })

  await saveWorkbook(wb, `${title.replace(/[^a-zA-Z0-9]/g, '_')}_${timestamp()}.xlsx`)
  sounds.export()
}

export async function exportMasterCSV({ days, periods, timetables, periodLabel }) {
  const teachingPeriods = periods.filter(p => !p.isBreak)
  const wb = new ExcelJS.Workbook()
  const ws = wb.addWorksheet('Master Timetable')

  const headers = ['Day', 'Period', 'Time', 'Class', 'Teacher', 'Subject', 'Room', 'Secondary Class', 'Secondary Subject', 'Secondary Teacher']
  const headerRow = ws.addRow(headers)
  headerRow.height = 25
  headerRow.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 11 }
    cell.fill = headerFill
    cell.alignment = { horizontal: 'center', vertical: 'middle' }
    cell.border = thinBorder
  })

  let rowIdx = 0
  for (const day of days) {
    for (const p of teachingPeriods) {
      const entries = timetables.filter(e => e.day === day && e.periodId === p.id)
      if (entries.length === 0) {
        const row = ws.addRow([day, p.name, `${p.start}-${p.end}`, '', '', '', '', '', '', ''])
        row.eachCell((cell, colNumber) => {
          cell.border = thinBorder
          cell.alignment = { horizontal: 'center', vertical: 'middle' }
          if (colNumber === 1) { cell.font = { bold: true } }
          if (rowIdx % 2 === 1) cell.fill = altFill
        })
        rowIdx++
      } else {
        for (const e of entries) {
          const row = ws.addRow([day, p.name, `${p.start}-${p.end}`, e.className, e.teacherName, e.subjectName, e.roomName, e.secondaryClassName || '', e.secondarySubjectName || '', e.secondaryTeacherName || ''])
          row.eachCell((cell, colNumber) => {
            cell.border = thinBorder
            cell.alignment = { horizontal: 'center', vertical: 'middle' }
            if (colNumber === 1) { cell.font = { bold: true } }
            if (colNumber === 4) { cell.font = { bold: true, color: { argb: 'FF1E40AF' } } }
            if (colNumber === 5) { cell.font = { color: { argb: 'FF059669' } } }
            if (rowIdx % 2 === 1) cell.fill = altFill
          })
          rowIdx++
        }
      }
    }
  }

  ws.columns.forEach((col, i) => {
    col.width = [10, 10, 12, 18, 18, 18, 12, 18, 18, 18][i] || 15
  })

  const suffix = periodLabel ? `_${periodLabel.replace(/[^a-zA-Z0-9]/g, '_')}` : ''
  await saveWorkbook(wb, `Master_Timetable${suffix}_${timestamp()}.xlsx`)
  sounds.export()
}

export function exportBulkPDF({ items, days, periods, school, paperSize, orientation, bulkType, periodLabel, getScheduleForClassFn }) {
  const pdf = new jsPDF({ orientation, unit: 'mm', format: paperSize })
  const pageW = pdf.internal.pageSize.getWidth()
  const pageH = pdf.internal.pageSize.getHeight()
  const isLandscape = orientation === 'landscape'

  items.forEach((item, index) => {
    if (index > 0) pdf.addPage()

    const itemDays = item.schedule?.days || days
    const itemPeriods = item.schedule?.periods || periods
    const teachingPeriods = itemPeriods.filter(p => !p.isBreak)

    let startY = 18
    if (school?.name) {
      const logoOffset = addLogoToPDF(pdf, school, pageW)
      pdf.setFontSize(14)
      pdf.setTextColor(30, 64, 175)
      pdf.text(school.name, pageW / 2, 12 + logoOffset, { align: 'center' })
      startY = 22 + logoOffset
    }

    const titlePrefix = bulkType === 'classes' ? 'Class' : 'Teacher'
    pdf.setFontSize(12)
    pdf.setTextColor(30, 64, 175)
    pdf.text(`${titlePrefix}: ${item.name}`, pageW / 2, startY, { align: 'center' })

    if (periodLabel) {
      pdf.setFontSize(8)
      pdf.setTextColor(80, 80, 80)
      pdf.text(periodLabel, pageW / 2, startY + 5, { align: 'center' })
      startY += 10
    } else {
      startY += 5
    }

    const head = [['Day / Period', ...teachingPeriods.map(p => p.name)]]
    const body = itemDays.map(day => {
      const row = [day]
      for (const p of teachingPeriods) {
        const cell = item.rows[day]?.[p.id]
        row.push(cell || '—')
      }
      return row
    })

    const bulkScale = pageW / 210
    const bulkMargin = 5 * bulkScale
    const bulkAvailableHeight = pageH - startY - 10 * bulkScale
    const bulkTotalRows = body.length + 1
    const bulkRowHeight = bulkAvailableHeight / bulkTotalRows
    autoTable(pdf, {
      head,
      body,
      startY,
      theme: 'grid',
      headStyles: {
        fillColor: [37, 99, 235],
        textColor: 255,
        fontSize: (isLandscape ? 8 : 7) * bulkScale,
        halign: 'center',
        minCellHeight: bulkRowHeight,
      },
      bodyStyles: {
        fontSize: (isLandscape ? 7 : 6) * bulkScale,
        halign: 'center',
        valign: 'middle',
        minCellHeight: bulkRowHeight,
      },
      alternateRowStyles: { fillColor: [239, 246, 255] },
      columnStyles: { 0: { fontStyle: 'bold', cellWidth: 25 * bulkScale, fillColor: [219, 234, 254] } },
      margin: { left: bulkMargin, right: bulkMargin },
    })

    pdf.setFontSize(7)
    pdf.setTextColor(150, 150, 150)
    pdf.text('Generated by Shikola Timetable Creator - Sepio Corp', pageW / 2, pageH - 5, { align: 'center' })
  })

  sounds.export()
  const suffix = periodLabel ? `_${periodLabel.replace(/[^a-zA-Z0-9]/g, '_')}` : ''
  pdf.save(`Bulk_${bulkType}_${paperSize}_${orientation}${suffix}_${timestamp()}.pdf`)
}

export async function exportBulkCSV({ items, days, periods, bulkType, periodLabel, getScheduleForClassFn }) {
  const wb = new ExcelJS.Workbook()
  const typeLabel = bulkType === 'classes' ? 'Class' : 'Teacher'

  for (const item of items) {
    const itemDays = item.schedule?.days || days
    const itemPeriods = item.schedule?.periods || periods
    const teachingPeriods = itemPeriods.filter(p => !p.isBreak)
    const sheetName = item.name.substring(0, 31).replace(/[\\/\?\*\[\]:]/g, '_')
    const ws = wb.addWorksheet(sheetName)

    const headers = ['Day / Period', ...teachingPeriods.map(p => `${p.name}\n(${p.start}-${p.end})`)]
    const headerRow = ws.addRow(headers)
    headerRow.height = 30
    headerRow.eachCell((cell) => {
      cell.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 11 }
      cell.fill = headerFill
      cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true }
      cell.border = thinBorder
    })

    itemDays.forEach((day, dayIdx) => {
      const rowData = [day]
      for (const p of teachingPeriods) {
        const cell = item.rows[day]?.[p.id]
        rowData.push(cell || '—')
      }
      const row = ws.addRow(rowData)
      row.height = 45
      row.eachCell((cell, colNumber) => {
        cell.border = thinBorder
        cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true }
        if (colNumber === 1) {
          cell.font = { bold: true, color: { argb: 'FF1E40AF' } }
          cell.fill = dayFill
        } else {
          cell.font = { size: 10 }
          if (dayIdx % 2 === 1) cell.fill = altFill
        }
      })
    })

    ws.columns.forEach((col, i) => {
      col.width = i === 0 ? 18 : 28
    })
  }

  const suffix = periodLabel ? `_${periodLabel.replace(/[^a-zA-Z0-9]/g, '_')}` : ''
  await saveWorkbook(wb, `Bulk_${bulkType}${suffix}_${timestamp()}.xlsx`)
  sounds.export()
}
