function escapeHtml(text) {
  if (!text) return ''
  const div = document.createElement('div')
  div.textContent = text
  return div.innerHTML
}

export function exportTimetableHTML({ title, subtitle, days, periods, rows, school, periodLabel }) {
  const teachingPeriods = periods.filter(p => !p.isBreak)
  const header = [
    school?.name ? `<div class="school-name">${escapeHtml(school.name)}</div>` : '',
    school?.motto ? `<div class="school-motto">${escapeHtml(school.motto)}</div>` : '',
    school?.address ? `<div class="school-address">${escapeHtml(school.address)}</div>` : '',
    `<div class="title">${escapeHtml(title)}</div>`,
    subtitle ? `<div class="subtitle">${escapeHtml(subtitle)}</div>` : '',
    periodLabel ? `<div class="period-label">${escapeHtml(periodLabel)}</div>` : '',
  ].join('\n')

  const tableHead = `<tr><th>Day / Period</th>` +
    teachingPeriods.map(p => `<th>${escapeHtml(p.name)}<br><span style="font-weight:400;font-size:10px">${escapeHtml(p.start)}-${escapeHtml(p.end)}</span></th>`).join('') +
    `</tr>`

  const tableBody = days.map(day => {
    const cells = teachingPeriods.map(p => {
      const cellText = rows[day]?.[p.id]
      return `<td><div class="cell-content">${escapeHtml(cellText) || '—'}</div></td>`
    }).join('')
    return `<tr><td>${escapeHtml(day)}</td>${cells}</tr>`
  }).join('')

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(title)}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; background: #f8fafc; color: #1e293b; padding: 24px; }
  .header { text-align: center; margin-bottom: 24px; }
  .school-name { font-size: 24px; font-weight: 700; color: #1e40af; }
  .school-motto { font-size: 14px; color: #64748b; margin-top: 4px; }
  .school-address { font-size: 12px; color: #94a3b8; margin-top: 2px; }
  .title { font-size: 20px; font-weight: 600; color: #2563eb; margin-top: 12px; }
  .subtitle { font-size: 14px; color: #64748b; margin-top: 4px; }
  .period-label { font-size: 12px; color: #94a3b8; margin-top: 4px; }
  table { width: 100%; border-collapse: collapse; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
  th { background: #2563eb; color: white; padding: 12px 8px; font-size: 13px; font-weight: 600; text-align: center; }
  th:first-child { background: #1e40af; }
  td { padding: 16px 8px; text-align: center; font-size: 12px; border: 1px solid #e2e8f0; vertical-align: middle; }
  td:first-child { font-weight: 600; color: #1e40af; background: #dbeafe; }
  tr:nth-child(even) td:not(:first-child) { background: #eff6ff; }
  .cell-content { white-space: pre-line; line-height: 1.4; }
  .footer { text-align: center; margin-top: 16px; font-size: 11px; color: #94a3b8; }
  @media print { body { padding: 0; } table { box-shadow: none; } }
</style>
</head>
<body>
  <div class="header">
    ${header}
  </div>
  <table>
    <thead>${tableHead}</thead>
    <tbody>${tableBody}</tbody>
  </table>
  <div class="footer">Generated by Shikola Timetable Creator - Sepio Corp</div>
</body>
</html>`

  const blob = new Blob([html], { type: 'text/html' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  const ts = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19)
  link.href = url
  link.download = `${title.replace(/[^a-zA-Z0-9]/g, '_')}_${ts}.html`
  link.click()
  URL.revokeObjectURL(url)
}

export function exportMasterHTML({ days, periods, timetables, school, periodLabel }) {
  const teachingPeriods = periods.filter(p => !p.isBreak)
  const header = [
    school?.name ? `<div class="school-name">${escapeHtml(school.name)}</div>` : '',
    `<div class="title">Master Timetable</div>`,
    periodLabel ? `<div class="period-label">${escapeHtml(periodLabel)}</div>` : '',
  ].join('\n')

  const tableHead = `<tr><th>Day / Period</th>` +
    teachingPeriods.map(p => `<th>${escapeHtml(p.name)}</th>`).join('') + `</tr>`

  const tableBody = days.map(day => {
    const cells = teachingPeriods.map(p => {
      const entries = timetables.filter(e => e.day === day && e.periodId === p.id)
      if (entries.length === 0) return `<td>—</td>`
      const text = entries.map(e => {
        let line = `${escapeHtml(e.className)}: ${escapeHtml(e.subjectName)} (${escapeHtml(e.teacherName)})`
        if (e.secondaryClassName) {
          line += `<br>→ ${escapeHtml(e.secondaryClassName)}: ${escapeHtml(e.secondarySubjectName || '')} (${escapeHtml(e.secondaryTeacherName || '')})`
        }
        return line
      }).join('<hr style="border:none;border-top:1px solid #e2e8f0;margin:4px 0">')
      return `<td><div class="cell-content">${text}</div></td>`
    }).join('')
    return `<tr><td>${escapeHtml(day)}</td>${cells}</tr>`
  }).join('')

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Master Timetable</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', system-ui, sans-serif; background: #f8fafc; color: #1e293b; padding: 24px; }
  .header { text-align: center; margin-bottom: 24px; }
  .school-name { font-size: 24px; font-weight: 700; color: #1e40af; }
  .title { font-size: 20px; font-weight: 600; color: #2563eb; margin-top: 12px; }
  .period-label { font-size: 12px; color: #94a3b8; margin-top: 4px; }
  table { width: 100%; border-collapse: collapse; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
  th { background: #2563eb; color: white; padding: 10px 6px; font-size: 12px; font-weight: 600; text-align: center; }
  th:first-child { background: #1e40af; }
  td { padding: 10px 6px; text-align: center; font-size: 10px; border: 1px solid #e2e8f0; vertical-align: top; }
  td:first-child { font-weight: 600; color: #1e40af; background: #dbeafe; }
  tr:nth-child(even) td:not(:first-child) { background: #eff6ff; }
  .cell-content { line-height: 1.5; }
  .footer { text-align: center; margin-top: 16px; font-size: 11px; color: #94a3b8; }
  @media print { body { padding: 0; } table { box-shadow: none; } }
</style>
</head>
<body>
  <div class="header">${header}</div>
  <table>
    <thead>${tableHead}</thead>
    <tbody>${tableBody}</tbody>
  </table>
  <div class="footer">Generated by Shikola Timetable Creator - Sepio Corp</div>
</body>
</html>`

  const blob = new Blob([html], { type: 'text/html' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  const ts = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19)
  link.href = url
  link.download = `Master_Timetable_${ts}.html`
  link.click()
  URL.revokeObjectURL(url)
}
